{% set name = "macapype" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9b62c1d502cea07e628c2667914f8bc75614aad253263a4a99bd38b8cca9b46f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - brain-slam
    - networkx >=2.0
    - nibabel
    - nilearn
    - nipype
    - numpy
    - pip
    - pybids
    - python
    - scikit-image
  run:
    - brain-slam
    - networkx >=2.0
    - nibabel
    - nilearn
    - nipype
    - numpy
    - pybids
    - python
    - scikit-image

test:
  imports:
    - examples
    - macapype
    - macapype.nodes
    - macapype.pipelines
    - macapype.utils

about:
  home: The package home page
  license: BSD 3
  license_family: BSD
  license_file: 
  summary: "Pipeline for anatomic processing for macaque"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - macatools
