name: (Release) Build Pipy, Dockerhub image and test

on:
  release:
    types: [released]

jobs:

  build-n-publish-pypi:
    name: Build and publish Python to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  docker-build:
    name: Build Docker image and Push to Docker Hub
    needs: build-n-publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: macatools/macapype

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-test:
    name: Running all existing pipelines in macapype_CI.zip
    needs: docker-build
    runs-on: self-hosted
    runs-on: self-hosted
    timeout-minutes: 1440

    steps:
      - uses: actions/checkout@v2
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |
            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""
            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""
            ls macapype_CI/marmo-marmobrain
            echo ""
            ls macapype_CI/baboon-cerimed-adrien
            echo ""

      - name: Running test pipeline macaque_prime-de indiv
        run: |
            docker run -i -v /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/macaque_prime-de/ -out /data/macaque_prime-de/results -soft ANTS -species macaque -indiv /data/macaque_prime-de/indiv_params_segment_macaque.json -sub 032140 -ses 001 -deriv -pad

      - name: Running test pipeline marmo-marmobrain indiv
        run: |
            docker run -i -v /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/marmo-marmobrain -out /data/marmo-marmobrain/results -soft ANTS -species marmo -indiv /data/marmo-marmobrain/indiv_params_segment_marmo.json -sub 8034 -ses 01 -deriv -pad

      - name: Running test pipeline baboon-cerimed-adrien indiv
        run: |
            docker run -i -v /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/baboon-cerimed-adrien -out /data/baboon-cerimed-adrien/results -soft ANTS -species baboon -indiv /data/baboon-cerimed-adrien/indiv_params_segment_baboon.json -sub Fidji -ses 01 -deriv -pad

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI
            sudo rm -f /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI.zip

