name: (Prerelease) Build Pipy, Dockerhub image and test

on:
  release:
    types: [prereleased]

jobs:

  build:

    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python  3.10.5
        uses: actions/setup-python@v2
        with:
          python-version:  3.10.5

      - name: Install dependencies
        run: |
            pip install -e .[doc]
            sudo apt-get install build-essential  graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

      - name: Test with pytest
        run:
            py.test --cov macapype --ignore=examples/ --ignore=run_examples/

      - name: Build the Doc 🔧
        run: |
          cd docs
          make clean
          make html
          touch _build/html/.nojekyll

      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/_build/html/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}

  build-n-publish-testpypi:
    name: Build and publish Python to Test PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  docker-build:
    name: Build Docker image and Push to Docker Hub
    needs: build-n-publish-testpypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: macatools/macapype

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile_testpypi_nomcr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-pretest-ants-marmo:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS marmo)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_marmo
            echo ""

      - name: Running test pipeline cerimed_marmo ANTS_noseg T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_marmo -out /data/cerimed_marmo/results -soft ANTS_robustreg_noseg -species marmo -sub Tresor -ses 01 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/macapype_ants/sub-Tresor/ses-01/anat/
            echo ""


      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results

  run-pretest-ants-marmoT2:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS marmo T1)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/CoSC5w5ATZextme --output macapype_CI_v2.1.zip
            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1


            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_marmo
            echo ""

      - name: Running test pipeline cerimed_marmo ANTS_noseg T1
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_marmo -out /data/cerimed_marmo/results -soft ANTS_noseg -species marmoT2 -sub Tresor -ses 01 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results/derivatives/macapype_ants/sub-Tresor/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_marmo/results


  run-pretest-ants-baboon:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_baboon
            echo ""

      - name: Running test pipeline cerimed_baboon ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_baboon -out /data/cerimed_baboon/results -soft ANTS_prep -species baboon -sub Prune -ses 3 -deriv -pad -dt T1 T2 -indiv /data/cerimed_baboon/indiv_params_segment_baboon.json

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results/derivatives/macapype_ants/sub-Prune/ses-3/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results

  run-pretest-ants-baboon3:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_baboon
            echo ""

      - name: Running test pipeline cerimed_baboon ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_baboon -out /data/cerimed_baboon/results3 -soft ANTS_prep -species baboon3 -sub Prune -ses 3 -deriv -pad -dt T1 T2 -indiv /data/cerimed_baboon/indiv_params_segment_baboon.json

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results3/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results3/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results3/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results3/derivatives/macapype_ants/sub-Prune/ses-3/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results3


  run-pretest-ants-baboon2:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_baboon
            echo ""

      - name: Running test pipeline cerimed_baboon ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_baboon -out /data/cerimed_baboon/results2 -soft ANTS_prep -species baboon2 -sub Prune -ses 2 -deriv -pad -dt T1 T2 -indiv /data/cerimed_baboon/indiv_params_segment_baboon.json

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results2/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results2/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results2/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results2/derivatives/macapype_ants/sub-Prune/ses-2/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results2

  run-pretest-ants-baboon1:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_baboon
            echo ""

      - name: Running test pipeline cerimed_baboon ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_baboon -out /data/cerimed_baboon/results1 -soft ANTS_prep -species baboon1 -sub Prune -ses 1 -deriv -pad -dt T1 T2 -indiv /data/cerimed_baboon/indiv_params_segment_baboon.json

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results1/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results1/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results1/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results1/derivatives/macapype_ants/sub-Prune/ses-1/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results1

  run-pretest-ants-baboon0:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_baboon
            echo ""

      - name: Running test pipeline cerimed_baboon ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_baboon -out /data/cerimed_baboon/results0 -soft ANTS_prep -species baboon0 -sub Prune -ses 0 -deriv -pad -dt T1 T2 -indiv /data/cerimed_baboon/indiv_params_segment_baboon.json

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results0/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results0/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results0/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results0/derivatives/macapype_ants/sub-Prune/ses-0/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_baboon/results0

  run-pretest-ants-macaque:
    name: Running all existing pipelines in macapype_CI_v2.1.zip (ANTS macaque)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.1.zip

            unzip -o macapype_CI_v2.1.zip -d macapype_CI_v2.1

            pwd
            echo ""

            ls macapype_CI_v2.1
            echo ""

            ls macapype_CI_v2.1/cerimed_macaque
            echo ""

      - name: Running test pipeline cerimed_macaque ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI_v2.1:/data macatools/macapype:latest segment_pnh -data /data/cerimed_macaque/ -out /data/cerimed_macaque/results -soft ANTS_robustreg_prep -species macaque -sub Stevie -ses 01 -deriv -pad -dt T1 T2 -nprocs 1

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_macaque/results/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_macaque/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_macaque/results/derivatives/macapype_ants/

            ls /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_macaque/results/derivatives/macapype_ants/sub-Stevie/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI_v2.1/cerimed_macaque/results

