name: (Prerelease) Build Pipy, Dockerhub image and test

on:
  release:
    types: [prereleased]

jobs:

  build-n-publish-testpypi:
    name: Build and publish Python to Test PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  docker-build:
    name: Build Docker image and Push to Docker Hub
    needs: build-n-publish-testpypi
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: macatools/macapype

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile_testpypi_nomcr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-pretest-ants-t1-marmo:
    name: Running all existing pipelines in macapype_CI.zip (ANTS marmo T1)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline marmo-marmobrain ANTS_noseg T1
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/marmo-marmobrain -out /data/marmo-marmobrain/results -soft ANTS_noseg -species marmo -sub Percy -ses 01 -deriv -pad -dt T1

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1/sub-Percy/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1/


  run-pretest-ants-marmo:
    name: Running all existing pipelines in macapype_CI.zip (ANTS marmo)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline marmo-marmobrain ANTS_noseg T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/marmo-marmobrain -out /data/marmo-marmobrain/results -soft ANTS_noseg -species marmo -sub Percy -ses 01 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1_t2/

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1_t2/sub-Percy/ses-01/anat/
            echo ""


      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_ants_t1_t2/


  run-pretest-ants-t1-baboon:
    name: Running all existing pipelines in macapype_CI.zip (ANTS T1 baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline baboon-cerimed-adrien ANTS_prep T1
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/baboon-cerimed-adrien -out /data/baboon-cerimed-adrien/results -soft ANTS_prep -species baboon -sub Fidji -ses 01 -deriv -pad -dt T1

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1/sub-Fidji/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1/



  run-pretest-ants-baboon:
    name: Running all existing pipelines in macapype_CI.zip (ANTS baboon)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline baboon-cerimed-adrien ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/baboon-cerimed-adrien -out /data/baboon-cerimed-adrien/results -soft ANTS_prep -species baboon -sub Fidji -ses 01 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1_t2/

            ls /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1_t2/sub-Fidji/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/baboon-cerimed-adrien/results/derivatives/macapype_crop_aladin_ants_t1_t2/



  run-pretest-ants-macaque-t1:
    name: Running all existing pipelines in macapype_CI.zip (ANTS macaque T1)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440


    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline macaque_prime-de ANTS_prep T1
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/macaque_prime-de/ -out /data/macaque_prime-de/results -soft ANTS_prep -species macaque -sub 032140 -ses 001 -deriv -pad -dt T1

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1/sub-032140/ses-001/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1/


  run-pretest-ants-macaque:
    name: Running all existing pipelines in macapype_CI.zip (ANTS macaque)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline macaque_prime-de ANTS_prep T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/macaque_prime-de/ -out /data/macaque_prime-de/results -soft ANTS_prep -species macaque -sub 032140 -ses 001 -deriv -pad -dt T1 T2 -nprocs 1

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1_t2/

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1_t2/sub-032140/ses-001/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf macaque_prime-de/results/derivatives/macapype_crop_aladin_ants_t1_t2


  run-pretest-spm-macaque:
    name: Running all existing pipelines in macapype_CI.zip (SPM_native macaque)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline macaque_prime-de SPM_native T1 T2
        run: |
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/macaque_prime-de -out /data/macaque_prime-de/results -soft SPM_native -species macaque -sub 032140 -ses 001 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_spm_t1_t2_native/sub-032140/ses-001/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/macaque_prime-de/results/derivatives/macapype_crop_aladin_spm_t1_t2_native

  run-pretest-spm-marmo:
    name: Running all existing pipelines in macapype_CI.zip (SPM_native marmo)
    needs:  docker-build
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |

            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            pwd
            echo ""

            ls macapype_CI
            echo ""

            ls macapype_CI/macaque_prime-de
            echo ""

            ls macapype_CI/marmo-marmobrain
            echo ""

      - name: Running test pipeline marmo-marmobrain SPM_native_prep T1 T2
        run: |

            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest segment_pnh -data /data/marmo-marmobrain -out /data/marmo-marmobrain/results -soft SPM_native -species marmo -sub Percy -ses 01 -deriv -pad -dt T1 T2

            ls /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_spm_t1_t2_native/sub-Percy/ses-01/anat/
            echo ""

      - name: Cleaning dataset
        run:
            sudo rm -rf /home/runner/work/macapype/macapype/macapype_CI/marmo-marmobrain/results/derivatives/macapype_crop_aladin_spm_t1_t2_native/
