name: Running all existing pipelines in macapype_CI.zip

on:
  release:
    types: [published]


  push:
    branches:
      - hotfix_NMT_version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull latest docker image
        run:
            docker pull macatools/macapype:latest

      - name: Download dataset
        run: |
            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=3NLBXgFGdxPBRC2&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI
            ls

      - name: Running all test pipelines
        run: |
            pwd
            echo ""
            ls macapype_CI
            echo ""
            ls macapype_CI/macaque_prime-de
            echo ""
            docker run -i -v /home/runner/work/macapype/macapype/macapype_CI:/data macatools/macapype:latest python /opt/packages/macapype/workflows/segment_pnh.py -data /data/macaque_prime-de/ -out /data/macaque_prime-de/results -soft ANTS -species macaque -indiv /data/macaque_prime-de/indiv_params_segment_macaque.json -sub 032140 -ses 001 -deriv
