
name: Checking unit-tests, PEP8 and standard pipeline congruency

on:

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python  3.10.5
        uses: actions/setup-python@v2
        with:
          python-version:  3.10.5

      - name: Install dependencies
        run: |
            pip install -e .[test]
            sudo apt-get install build-essential  graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

      - name: Test with pytest
        run:
            py.test --cov macapype --ignore=examples/ --ignore=run_examples/

      - name: Flake8
        run:
            flake8 --count macapype

      - name: Download dataset
        run: |
            curl https://amubox.univ-amu.fr/public.php/dav/files/YGrYLjRb8AyQoQp --output macapype_CI_v2.zip
            unzip -o macapype_CI_v2.zip -d macapype_CI_v2

      - name: Running all test pipelines (macaque)
        run: |
            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001  -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001  -dt T1 T2

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001  -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001  -dt T1 T2

      - name: Running all test pipelines (macaque deriv)
        run: |
            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001 -deriv -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001 -deriv -dt T1 T2

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001 -deriv -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001 -deriv -dt T1 T2

      - name: Running all test pipelines (macaque deriv pad)
        run: |

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001 -deriv -pad -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft ANTS_test -species macaque -sub Stevie -ses 001 -deriv -pad -dt T1 T2

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001 -deriv -pad -dt T1

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_macaque/results -soft SPM_native_test -species macaque -sub Stevie -ses 001 -deriv -pad -dt T1 T2

      - name: Running some test pipelines (baboon / marmo)
        run: |

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_baboon -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_baboon/results -soft ANTS_test -species baboon -sub Prune -ses 3 -deriv -pad -dt T1 T2

            python workflows/segment_pnh.py -data /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_marmo -out /home/runner/work/macapype/macapype/macapype_CI_v2/cerimed_marmo/results -soft ANTS_test -species marmo -sub Tresor -ses 01 -deriv -pad -dt T1 T2
