name: Running all existing pipelines in macapype_CI.zip

on:
  release:
    types: [published]


  push:
    branches:
      - hotfix_NMT_version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
            sudo apt-get install wget zip

            pip install codecov pytest pytest-cov
            pip install flake8

            sudo apt-get install graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

            pip install -e .
      - name: Download dataset
        run:
            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=3NLBXgFGdxPBRC2&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

            ls macapype_CI
