name: Running all existing pipelines in macapype_CI.zip

on:
  release:
    types: [published]


  push:
    branches:
      - hotfix_NMT_version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
            sudo apt-get install wget zip

            pip install codecov pytest pytest-cov
            pip install flake8

            sudo apt-get install graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

            pip install -e .

      - name: Running all test pipelines
        run: |
            python workflows/segment_pnh.py -data macapype_CI/macaque_prime-de/ -out macapype_CI/macaque_prime-de/ -soft ANTS_test -species macaque -indiv macapype_CI/macaque_prime-de/indiv_params_segment_macaque.json -sub 032140 -ses 001 -deriv
