
name: Checking unit-tests, PEP8 and standard pipeline congruency

on:

  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build package, unittest and PEP8 check
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: |
            pip install codecov pytest pytest-cov
            pip install -e .
            pip install flake8
            sudo apt-get install build-essential  graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

      - name: Test with pytest
        run:
            py.test --cov macapype --ignore=examples/ --ignore=run_examples/

      - name: Flake8
        run:
            flake8 --count macapype

  run-tests:
    name: Running all existing test pipelines in macapype_CI.zip
    needs: build
    timeout-minutes: 1440

    strategy:
        matrix:
            soft: [ANTS, ANTS_T1, SPM, SPM_T1, ANTS_template, ANTS_template_T1, SPM_native, SPM_native_T1]

    steps:
      - name: Download dataset
        run: |
            wget --no-check-certificate --content-disposition  "https://amubox.univ-amu.fr/public.php?service=files&t=KJ2L5j6L6orPXxM&download" -O macapype_CI.zip
            unzip -o macapype_CI.zip -d macapype_CI

      - name: Running all test pipelines
        run: |
            python workflows/segment_pnh.py -data /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI/macaque_prime-de -out /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI/macaque_prime-de/results -soft {{matrix.soft}}_test -species macaque -sub 032140 -ses 001 -deriv

            python workflows/segment_pnh.py -data /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI/macaque_prime-de -out /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI/macaque_prime-de/results -soft {{matrix.soft}}_test -species macaque -indiv /home/ubuntu/actions-runner/_work/macapype/macapype/macapype_CI/macaque_prime-de/indiv_params_segment_macaque.json -sub 032140 -ses 001 -deriv
