name: "Test and deploy"

on:
  push:
    branches:
        [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python  3.10.5
        uses: actions/setup-python@v2
        with:
          python-version:  3.10.5

      - name: Install dependencies
        run: |
            pip install -e .[doc]
            sudo apt-get install build-essential  graphviz libgraphviz-dev
            pip install --upgrade pygraphviz graphviz

      - name: Test with pytest
        run:
            py.test --cov macapype --ignore=examples/ --ignore=run_examples/

      - name: Build the Doc 🔧
        run: |
          cd docs
          make clean
          make html
          touch _build/html/.nojekyll

      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs/_build/html/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
